spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_db
    username: root
    password: db_admin_2718
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true